$dbd_oracle_mm_opts = {
                        'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                        'PREREQ_PM' => {
                                         'DBI' => '1.51'
                                       },
                        'DEFINE' => ' -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"19.1.0.0\\" -DORA_OCI_102 -DORA_OCI_112',
                        'clean' => {
                                     'FILES' => 'xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*'
                                   },
                        'OBJECT' => '$(O_FILES)',
                        'META_MERGE' => {
                                          'build_requires' => {
                                                                'ExtUtils::MakeMaker' => 0,
                                                                'Test::Simple' => '0.90',
                                                                'DBI' => '1.51'
                                                              },
                                          'resources' => {
                                                           'bugtracker' => {
                                                                             'mailto' => 'bug-dbd-oracle at rt.cpan.org',
                                                                             'web' => 'http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle'
                                                                           },
                                                           'repository' => {
                                                                             'url' => 'git://github.com/yanick/DBD-Oracle.git',
                                                                             'web' => 'http://github.com/yanick/DBD-Oracle/tree',
                                                                             'type' => 'git'
                                                                           },
                                                           'homepage' => 'http://search.cpan.org/dist/DBD-Oracle'
                                                         },
                                          'configure_requires' => {
                                                                    'DBI' => '1.51'
                                                                  }
                                        },
                        'AUTHOR' => 'Tim Bunce (dbi-users@perl.org)',
                        'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                        'DIR' => [],
                        'LICENSE' => 'perl',
                        'INC' => '-I%ORACLE_HOME%/oci/include -I%ORACLE_HOME%/rdbms/demo -I%ORACLE_HOME%\\perl\\site\\lib\\auto\\DBI',
                        'LIBS' => [
                                    '-L%ORACLE_HOME%/oci/LIB/MSVC OCI'
                                  ],
                        'NAME' => 'DBD::Oracle',
                        'dist' => {
                                    'PREOP' => '$(MAKE) -f Makefile.old distdir',
                                    'COMPRESS' => 'gzip -v9',
                                    'SUFFIX' => 'gz',
                                    'DIST_DEFAULT' => 'clean distcheck disttest tardist'
                                  }
                      };
$dbd_oracle_mm_self = bless( {
                               'TEST_S' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e test_s --',
                               'MAN3EXT' => '3',
                               'PERM_RW' => 644,
                               'INST_AUTODIR' => '$(INST_LIB)\\auto\\$(FULLEXT)',
                               'FIRST_MAKEFILE' => 'Makefile',
                               'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                               'INSTALLSITESCRIPT' => '$(INSTALLSCRIPT)',
                               'PMLIBDIRS' => [
                                                'lib'
                                              ],
                               'PERL_ARCHIVE_AFTER' => '',
                               'DIST_CP' => 'best',
                               'INSTALLVENDORSCRIPT' => '',
                               'MOD_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Install -e "install([ from_to => {@ARGV}, verbose => \'$(VERBINST)\', uninstall_shadows => \'$(UNINST)\', dir_mode => \'$(PERM_DIR)\' ]);" --',
                               'AR_STATIC_ARGS' => 'cr',
                               'PARENT_NAME' => 'DBD',
                               'O_FILES' => [
                                              'Oracle.obj',
                                              'dbdimp.obj',
                                              'oci8.obj'
                                            ],
                               'ABSPERL' => '$(PERL)',
                               'BUILD_REQUIRES' => {},
                               'VENDORARCHEXP' => '',
                               'SO' => 'dll',
                               'PERL_SRC' => undef,
                               'INSTALLSITEARCH' => '%ORACLE_HOME%\\perl\\site\\lib',
                               'MM_Win32_VERSION' => '7.34',
                               'XS_VERSION' => '1.74',
                               'FULL_AR' => '',
                               'PERL' => '"%ORACLE_HOME%\\perl\\bin\\perl.exe"',
                               'PERL_LIB' => '%ORACLE_HOME%\\perl\\lib',
                               'clean' => $dbd_oracle_mm_opts->{'clean'},
                               'TARFLAGS' => 'cvf',
                               'DEFINE' => ' -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"19.1.0.0\\" -DORA_OCI_102 -DORA_OCI_112',
                               'PERM_RWX' => 755,
                               'VERSION_SYM' => '1_74',
                               'INST_MAN1DIR' => 'blib\\man1',
                               'PERL_ARCHLIB' => '%ORACLE_HOME%\\perl\\lib',
                               'RESULT' => [
                                             '# This Makefile is for the DBD::Oracle extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.34 (Revision: 73400) from the contents of
# Makefile.PL. Don\'t edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: ()
#
',
                                             '#   MakeMaker Parameters:
',
                                             '#     ABSTRACT_FROM => q[lib/DBD/Oracle.pm]',
                                             '#     AUTHOR => [q[Tim Bunce (dbi-users@perl.org)]]',
                                             '#     BUILD_REQUIRES => {  }',
                                             '#     CONFIGURE_REQUIRES => {  }',
                                             '#     DEFINE => q[ -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"19.1.0.0\\" -DORA_OCI_102 -DORA_OCI_112]',
                                             '#     DIR => []',
                                             '#     INC => q[-I%ORACLE_HOME%/oci/include -I%ORACLE_HOME%/rdbms/demo -I%ORACLE_HOME%\\perl\\site\\lib\\auto\\DBI]',
                                             '#     LIBS => [q[-L%ORACLE_HOME%/oci/LIB/MSVC OCI]]',
                                             '#     LICENSE => q[perl]',
                                             '#     META_MERGE => { build_requires=>{ DBI=>q[1.51], ExtUtils::MakeMaker=>q[0], Test::Simple=>q[0.90] }, configure_requires=>{ DBI=>q[1.51] }, resources=>{ bugtracker=>{ mailto=>q[bug-dbd-oracle at rt.cpan.org], web=>q[http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Oracle] }, homepage=>q[http://search.cpan.org/dist/DBD-Oracle], repository=>{ type=>q[git], url=>q[git://github.com/yanick/DBD-Oracle.git], web=>q[http://github.com/yanick/DBD-Oracle/tree] } } }',
                                             '#     NAME => q[DBD::Oracle]',
                                             '#     OBJECT => q[$(O_FILES)]',
                                             '#     PREREQ_PM => { DBI=>q[1.51] }',
                                             '#     TEST_REQUIRES => {  }',
                                             '#     VERSION_FROM => q[lib/DBD/Oracle.pm]',
                                             '#     clean => { FILES=>q[xstmp.c Oracle.xsi dll.base dll.exp sqlnet.log libOracle.def mk.pm DBD_ORA_OBJ.*] }',
                                             '#     dist => { COMPRESS=>q[gzip -v9], DIST_DEFAULT=>q[clean distcheck disttest tardist], PREOP=>q[$(MAKE) -f Makefile.old distdir], SUFFIX=>q[gz] }',
                                             '
# --- MakeMaker post_initialize section:'
                                           ],
                               'RCS_LABEL' => 'rcs -Nv$(VERSION_SYM): -q',
                               'XS_VERSION_MACRO' => 'XS_VERSION',
                               'PERL_ARCHLIBDEP' => '%ORACLE_HOME%\\perl\\lib',
                               'CC' => 'cl',
                               'ARGS' => {
                                           'LICENSE' => 'perl',
                                           'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                                           'NAME' => 'DBD::Oracle',
                                           'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                                           'INC' => '-I%ORACLE_HOME%/oci/include -I%ORACLE_HOME%/rdbms/demo -I%ORACLE_HOME%\\perl\\site\\lib\\auto\\DBI',
                                           'dist' => $dbd_oracle_mm_opts->{'dist'},
                                           'PREREQ_PM' => $dbd_oracle_mm_opts->{'PREREQ_PM'},
                                           'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                                           'OBJECT' => '$(O_FILES)',
                                           'clean' => $dbd_oracle_mm_opts->{'clean'},
                                           'DEFINE' => ' -DUTF8_SUPPORT -DORA_OCI_VERSION=\\"19.1.0.0\\" -DORA_OCI_102 -DORA_OCI_112',
                                           'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                                           'ABSTRACT_FROM' => 'lib/DBD/Oracle.pm',
                                           'AUTHOR' => [
                                                         'Tim Bunce (dbi-users@perl.org)'
                                                       ]
                                         },
                               'SITEARCHEXP' => '%ORACLE_HOME%\\perl\\site\\lib',
                               'INSTALLPRIVLIB' => '%ORACLE_HOME%\\perl\\lib',
                               'NAME' => 'DBD::Oracle',
                               'TEST_REQUIRES' => {},
                               'MAP_TARGET' => 'perl',
                               'DIST_DEFAULT' => 'tardist',
                               'PM' => {
                                         'lib/DBD/Oracle/Troubleshooting.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Win32.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Win32.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Hpux.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Hpux.pod',
                                         'lib/DBD/Oracle/Object.pm' => 'blib\\lib\\DBD\\Oracle\\Object.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Cygwin.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Cygwin.pod',
                                         'lib/DBD/Oracle.pm' => 'blib\\lib\\DBD\\Oracle.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Aix.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Aix.pod',
                                         'lib/DBD/Oracle/GetInfo.pm' => 'blib\\lib\\DBD\\Oracle\\GetInfo.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Macos.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Macos.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Vms.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Vms.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Linux.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Linux.pod',
                                         'mk.pm' => '$(INST_LIB)\\DBD\\mk.pm',
                                         'lib/DBD/Oracle/Troubleshooting/Win64.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Win64.pod',
                                         'lib/DBD/Oracle/Troubleshooting/Sun.pod' => 'blib\\lib\\DBD\\Oracle\\Troubleshooting\\Sun.pod'
                                       },
                               'DESTINSTALLMAN3DIR' => '$(DESTDIR)$(INSTALLMAN3DIR)',
                               'MM_VERSION' => '7.34',
                               'LDDLFLAGS' => '-dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"%ORACLE_HOME%\\perl\\lib\\CORE"  -machine:AMD64',
                               'ZIP' => 'zip',
                               'PERLPREFIX' => '%ORACLE_HOME%\\perl',
                               'AUTHOR' => $dbd_oracle_mm_self->{'ARGS'}{'AUTHOR'},
                               'COMPRESS' => 'gzip --best',
                               'INSTALLDIRS' => 'site',
                               'VERSION_MACRO' => 'VERSION',
                               'DLSRC' => 'dl_win32.xs',
                               'DESTINSTALLSITEBIN' => '$(DESTDIR)$(INSTALLSITEBIN)',
                               'FULLPERL' => '"%ORACLE_HOME%\\perl\\bin\\perl.exe"',
                               'H' => [
                                        'Oracle.h',
                                        'dbdimp.h',
                                        'dbivport.h',
                                        'ocitrace.h'
                                      ],
                               'MAKE' => 'nmake',
                               'NAME_SYM' => 'DBD_Oracle',
                               'DESTINSTALLMAN1DIR' => '$(DESTDIR)$(INSTALLMAN1DIR)',
                               'CHMOD' => '$(ABSPERLRUN) -MExtUtils::Command -e chmod --',
                               'PREFIX' => '$(SITEPREFIX)',
                               'UNINSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e uninstall --',
                               'POSTOP' => '$(NOECHO) $(NOOP)',
                               'dist' => $dbd_oracle_mm_opts->{'dist'},
                               'LICENSE' => 'perl',
                               'PERL_CORE' => 0,
                               'VENDORLIBEXP' => '',
                               'VERSION_FROM' => 'lib/DBD/Oracle.pm',
                               'INSTALLVENDORBIN' => '',
                               'ECHO' => '$(ABSPERLRUN) -l -e "binmode STDOUT, qq{:raw}; print qq{@ARGV}" --',
                               'DESTINSTALLSITEMAN3DIR' => '$(DESTDIR)$(INSTALLSITEMAN3DIR)',
                               'MAKEFILE' => 'Makefile',
                               'SITEPREFIX' => '%ORACLE_HOME%\\perl\\site',
                               'DESTINSTALLSITEMAN1DIR' => '$(DESTDIR)$(INSTALLSITEMAN1DIR)',
                               'MAN3PODS' => {
                                               'lib/DBD/Oracle/Troubleshooting/Cygwin.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Cygwin.$(MAN3EXT)',
                                               'lib/DBD/Oracle.pm' => '$(INST_MAN3DIR)\\DBD.Oracle.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Hpux.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Hpux.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Object.pm' => '$(INST_MAN3DIR)\\DBD.Oracle.Object.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Win32.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Win32.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Macos.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Macos.$(MAN3EXT)',
                                               'lib/DBD/Oracle/GetInfo.pm' => '$(INST_MAN3DIR)\\DBD.Oracle.GetInfo.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Aix.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Aix.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Win64.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Win64.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Vms.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Vms.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Linux.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Linux.$(MAN3EXT)',
                                               'lib/DBD/Oracle/Troubleshooting/Sun.pod' => '$(INST_MAN3DIR)\\DBD.Oracle.Troubleshooting.Sun.$(MAN3EXT)'
                                             },
                               'PERL_INCDEP' => '%ORACLE_HOME%\\perl\\lib\\CORE',
                               'INST_STATIC' => '$(INST_ARCHAUTODIR)\\$(BASEEXT)$(LIB_EXT)',
                               'INST_MAN3DIR' => 'blib\\man3',
                               'INSTALLSITEBIN' => '%ORACLE_HOME%\\perl\\bin',
                               'INSTALLSITELIB' => '%ORACLE_HOME%\\perl\\site\\lib',
                               'SUFFIX' => '.gz',
                               'NOOP' => 'rem',
                               'EXE_EXT' => '.exe',
                               'INST_ARCHAUTODIR' => '$(INST_ARCHLIB)\\auto\\$(FULLEXT)',
                               'LDFLAGS' => '-nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"%ORACLE_HOME%\\perl\\lib\\CORE"  -machine:AMD64',
                               'INSTALLBIN' => '%ORACLE_HOME%\\perl\\bin',
                               'DESTINSTALLPRIVLIB' => '$(DESTDIR)$(INSTALLPRIVLIB)',
                               'UMASK_NULL' => 'umask 0',
                               'MAKE_APERL_FILE' => 'Makefile.aperl',
                               'INSTALLSITEMAN1DIR' => '$(INSTALLMAN1DIR)',
                               'WARN_IF_OLD_PACKLIST' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e warn_if_old_packlist --',
                               'NOECHO' => '@',
                               'DLBASE' => '$(BASEEXT)',
                               'ABSTRACT' => 'Oracle database driver for the DBI module',
                               'DESTINSTALLARCHLIB' => '$(DESTDIR)$(INSTALLARCHLIB)',
                               'EXTRALIBS' => '"%ORACLE_HOME%\\oci\\LIB\\MSVC\\OCI.lib" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\\\lib\\x64\\oldnames.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\kernel32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\user32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\gdi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\winspool.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\comdlg32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\advapi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\shell32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\ole32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\oleaut32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\netapi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\uuid.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\ws2_32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\mpr.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\winmm.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\version.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\odbc32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\odbccp32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\comctl32.lib" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\\\lib\\x64\\msvcrt.lib" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\\\lib\\x64\\vcruntime.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\ucrt\\x64\\ucrt.lib"',
                               'TRUE' => '$(ABSPERLRUN)  -e "exit 0" --',
                               'EQUALIZE_TIMESTAMP' => '$(ABSPERLRUN) -MExtUtils::Command -e eqtime --',
                               'OBJ_EXT' => '.obj',
                               'FALSE' => '$(ABSPERLRUN)  -e "exit 1" --',
                               'MAKEFILE_OLD' => 'Makefile.old',
                               'FULLPERLRUN' => '$(FULLPERL)',
                               'INSTALLMAN3DIR' => '%ORACLE_HOME%\\perl\\man\\man3',
                               'LINKTYPE' => 'dynamic',
                               'OBJECT' => '$(O_FILES)',
                               'INST_BOOT' => '$(INST_ARCHAUTODIR)\\$(BASEEXT).bs',
                               'PERLMAINCC' => '$(CC)',
                               'INSTALLVENDORARCH' => '',
                               'INST_ARCHLIB' => 'blib\\arch',
                               'INST_BIN' => 'blib\\bin',
                               'LDFROM' => '$(OBJECT)',
                               'OSVERS' => '6.3.9600',
                               'VERSION' => '1.74',
                               'ZIPFLAGS' => '-r',
                               'DEV_NULL' => '> NUL',
                               'CI' => 'ci -u',
                               'DISTVNAME' => 'DBD-Oracle-1.74',
                               'VERBINST' => 0,
                               'DESTINSTALLVENDORARCH' => '$(DESTDIR)$(INSTALLVENDORARCH)',
                               'CONFIG' => [
                                             'ar',
                                             'cc',
                                             'cccdlflags',
                                             'ccdlflags',
                                             'dlext',
                                             'dlsrc',
                                             'exe_ext',
                                             'full_ar',
                                             'ld',
                                             'lddlflags',
                                             'ldflags',
                                             'libc',
                                             'lib_ext',
                                             'obj_ext',
                                             'osname',
                                             'osvers',
                                             'ranlib',
                                             'sitelibexp',
                                             'sitearchexp',
                                             'so',
                                             'vendorarchexp',
                                             'vendorlibexp'
                                           ],
                               'CP' => '$(ABSPERLRUN) -MExtUtils::Command -e cp --',
                               'BSLOADLIBS' => '',
                               'DESTINSTALLVENDORMAN1DIR' => '$(DESTDIR)$(INSTALLVENDORMAN1DIR)',
                               'C' => [
                                        'Oracle.c',
                                        'dbdimp.c',
                                        'oci8.c'
                                      ],
                               'PREREQ_PM' => {
                                                'DBI' => '1.51'
                                              },
                               'MAKEMAKER' => '%ORACLE_HOME%/perl/lib/ExtUtils/MakeMaker.pm',
                               'RANLIB' => 'rem',
                               'MKPATH' => '$(ABSPERLRUN) -MExtUtils::Command -e mkpath --',
                               'INST_LIBDIR' => '$(INST_LIB)\\DBD',
                               'DESTINSTALLSITESCRIPT' => '$(DESTDIR)$(INSTALLSITESCRIPT)',
                               'MACROEND' => '',
                               'INSTALLMAN1DIR' => '%ORACLE_HOME%\\perl\\man\\man1',
                               'SKIPHASH' => {},
                               'DIR' => $dbd_oracle_mm_opts->{'DIR'},
                               'OSNAME' => 'MSWin32',
                               'PERLRUN' => '$(PERL)',
                               'INST_LIB' => 'blib\\lib',
                               'DESTINSTALLVENDORSCRIPT' => '$(DESTDIR)$(INSTALLVENDORSCRIPT)',
                               'CCDLFLAGS' => ' ',
                               'INSTALLVENDORMAN3DIR' => '',
                               'LIB_EXT' => '.lib',
                               'INSTALLVENDORMAN1DIR' => '',
                               'TOUCH' => '$(ABSPERLRUN) -MExtUtils::Command -e touch --',
                               'INSTALLSCRIPT' => '%ORACLE_HOME%\\perl\\bin',
                               'ABSPERLRUNINST' => '$(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'DESTINSTALLBIN' => '$(DESTDIR)$(INSTALLBIN)',
                               'LIBPERL_A' => 'libperl.lib',
                               'XS' => {
                                         'Oracle.xs' => 'Oracle.c'
                                       },
                               'DESTINSTALLSCRIPT' => '$(DESTDIR)$(INSTALLSCRIPT)',
                               'LD' => 'link',
                               'LIBS' => $dbd_oracle_mm_opts->{'LIBS'},
                               'INC' => '-I%ORACLE_HOME%/oci/include -I%ORACLE_HOME%/rdbms/demo -I%ORACLE_HOME%\\perl\\site\\lib\\auto\\DBI',
                               'PERL_INC' => '%ORACLE_HOME%\\perl\\lib\\CORE',
                               'LIBC' => 'ucrt.lib',
                               'MACROSTART' => '',
                               'PMLIBPARENTDIRS' => [
                                                      'lib'
                                                    ],
                               'SITELIBEXP' => '%ORACLE_HOME%\\perl\\site\\lib',
                               'DLEXT' => 'dll',
                               'INST_SCRIPT' => 'blib\\script',
                               'MM_REVISION' => 73400,
                               'ECHO_N' => '$(ABSPERLRUN)  -e "print qq{@ARGV}" --',
                               'XS_DEFINE_VERSION' => '-D$(XS_VERSION_MACRO)=\\"$(XS_VERSION)\\"',
                               'DESTINSTALLSITEARCH' => '$(DESTDIR)$(INSTALLSITEARCH)',
                               'CP_NONEMPTY' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e cp_nonempty --',
                               'TO_UNIX' => '$(NOECHO) $(NOOP)',
                               'VENDORPREFIX' => '',
                               'FULLPERLRUNINST' => '$(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'PREOP' => '$(NOECHO) $(NOOP)',
                               'TEST_F' => '$(ABSPERLRUN) -MExtUtils::Command -e test_f --',
                               'BASEEXT' => 'Oracle',
                               'INST_ARCHLIBDIR' => '$(INST_ARCHLIB)\\DBD',
                               'MAN1EXT' => '1',
                               'CCCDLFLAGS' => ' ',
                               'INSTALLVENDORLIB' => '',
                               'MV' => '$(ABSPERLRUN) -MExtUtils::Command -e mv --',
                               'PERM_DIR' => 755,
                               'DISTNAME' => 'DBD-Oracle',
                               'FULLEXT' => 'DBD\\Oracle',
                               'PERLRUNINST' => '$(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"',
                               'INST_DYNAMIC' => '$(INST_ARCHAUTODIR)\\$(DLBASE).$(DLEXT)',
                               'UNINST' => 0,
                               'PL_FILES' => {},
                               'PERL_ARCHIVEDEP' => '$(PERL_INCDEP)\\perl528.lib',
                               'CONFIGURE_REQUIRES' => {},
                               'AR' => 'lib -ltcg',
                               'DESTDIR' => '',
                               'BOOTDEP' => '',
                               'DOC_INSTALL' => '$(ABSPERLRUN) -MExtUtils::Command::MM -e perllocal_install --',
                               'PERL_ARCHIVE' => '$(PERL_INC)\\perl528.lib',
                               'DESTINSTALLVENDORMAN3DIR' => '$(DESTDIR)$(INSTALLVENDORMAN3DIR)',
                               'LD_RUN_PATH' => '',
                               'FIXIN' => 'pl2bat.bat',
                               'INSTALLARCHLIB' => '%ORACLE_HOME%\\perl\\lib',
                               'EXPORT_LIST' => '$(BASEEXT).def',
                               'DESTINSTALLVENDORBIN' => '$(DESTDIR)$(INSTALLVENDORBIN)',
                               'DESTINSTALLSITELIB' => '$(DESTDIR)$(INSTALLSITELIB)',
                               'META_MERGE' => $dbd_oracle_mm_opts->{'META_MERGE'},
                               'DEFINE_VERSION' => '-D$(VERSION_MACRO)=\\"$(VERSION)\\"',
                               'LDLOADLIBS' => '"%ORACLE_HOME%\\oci\\LIB\\MSVC\\OCI.lib" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\\\lib\\x64\\oldnames.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\kernel32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\user32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\gdi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\winspool.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\comdlg32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\advapi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\shell32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\ole32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\oleaut32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\netapi32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\uuid.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\ws2_32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\mpr.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\winmm.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\version.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\odbc32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\odbccp32.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64\\comctl32.lib" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\\\lib\\x64\\msvcrt.lib" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\\\lib\\x64\\vcruntime.lib" "C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\ucrt\\x64\\ucrt.lib"',
                               'INSTALLSITEMAN3DIR' => '$(INSTALLMAN3DIR)',
                               'RM_F' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_f --',
                               'DESTINSTALLVENDORLIB' => '$(DESTDIR)$(INSTALLVENDORLIB)',
                               'ABSPERLRUN' => '$(ABSPERL)',
                               'USEMAKEFILE' => '-f',
                               'DIRFILESEP' => '^\\',
                               'SHAR' => 'shar',
                               'TAR' => 'tar',
                               'HAS_LINK_CODE' => 1,
                               'RM_RF' => '$(ABSPERLRUN) -MExtUtils::Command -e rm_rf --'
                             }, 'PACK001' );
